### ISSUE TITLE
No links in the text where it states "here" (edit: 3x)

### ISSUE THREAD

**Issue by 0PK** [matrix-io/matrixio-alexa-sdk-guide#1]
Links missing in the text.
E.g. "... in this case see guide on how to ssh here."
I cannot click on "here".

**Comment by yoelrc88** [comment]
Thank you, just fixed.

**Comment by 0PK** [comment]
You missed another: "If not, follow step-by-step instructions here"

**Comment by 0PK** [comment]
And: "Check here If you need help editing the file"

**Comment by yoelrc88** [comment]
Done!. Thanks again.
